### ISSUE TITLE
[Build] aiter fails to compile on ROCm 7.0/7.1 — opus `__builtin_amdgcn_tensor_load_to_lds` needs ROCm 7.2 clang

### ISSUE THREAD

**Issue by sunway513** [ROCm/aiter#4077]
## Summary
Building aiter from current `main` / `release/v0.1.17` (@ `68b5f7be`) for `gfx942;gfx950` **fails on ROCm 7.0 and 7.1 toolchains**, but **succeeds on ROCm 7.2**. This blocks the ROCm 7.0/7.1 wheels for the v0.1.17 release (the 6-wheel matrix currently reduces to rocm7.2 cp310/cp312 only).

`v0.1.16` (0730b33f) built cleanly on all of 7.0 / 7.1 / 7.2, so this is a **new build regression in v0.1.17**.

## Error (ROCm 7.1 / 7.0 builder, `pytorch/manylinux2_28-builder:rocm7.1`)
Compiling `csrc/kernels/activation_kernels.cu` / `activation_pybind.cu` (module_activation):
```
csrc/include/opus/opus.hpp:2478:13: error: use of undeclared identifier '__builtin_amdgcn_tensor_load_to_lds';
    did you mean '__builtin_amdgcn_global_load_lds'?
csrc/include/opus/opus.hpp:2478:13: error: argument to '__builtin_amdgcn_global_load_lds' must be a constant integer
csrc/include/opus/opus.hpp:2480:147: error: integral constant expression must have integral or unscoped
    enumeration type, not 'impl::tdm_sg2_vec' (vector of 4 'i32_t' values)
```
The `__builtin_amdgcn_tensor_load_to_lds` (TDM tensor-load-to-LDS) builtin only exists in the ROCm 7.2 clang; the 7.0/7.1 clang does not know it, so the header fails to compile regardless of offload arch.

## Likely origin
opus.hpp changes around 07-01 that added the tensor-load path — candidates: #3856 (opus gfx950 MoE stage2) and/or #3517 (opus feature enable). `git log csrc/include/opus/opus.hpp` should pin it.

## Ask
@carlushuang — could you **guard the `tensor_load_to_lds` path in `opus.hpp` by compiler/arch support** so it compiles (with a fallback) on ROCm 7.0/7.1 clang? Same pattern as #3860 ("arch-guard fp8/bf8 packed-cvt builtins for RDNA3/3.5"). Please fix on `main`; we will cherry-pick into `release/v0.1.17`.

## Repro
```
docker run --rm -v $PWD:/w pytorch/manylinux2_28-builder:rocm7.1 bash -c   'cd /w && PREBUILD_KERNELS=1 GPU_ARCHS="gfx942;gfx950" MAX_JOBS=32    /opt/python/cp312-cp312/bin/python setup.py bdist_wheel'
```
(fails at module_activation; same on rocm7.0; passes on rocm7.2)
